# H2 (desarrollo)
spring.datasource.url=jdbc:h2:file:./data/tvt;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# Subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
# Carpeta donde se guardan comprobantes, fractales y contratos
app.upload.dir=./uploads/

# Seguridad admin (usuario básico)
app.admin.username=admin
app.admin.password=1234

app.base-url=http://localhost:8080